# Site Settings
baseurl: ""
url : "https://madmatvey.github.io"

# Blog Settings
theme_settings :
  title : Eugene Leontev
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Eugene Leontev
    description : Ruby developer. Tech entrepreneur.
    experience :
      - start : 2018-08-20
        experience : Appbooster, Ruby developer
      - start : 2018-06-20
        end : 2018-01-18
        experience : Butupper, Ruby developer
      - start : 2016-06-20
        end : 2017-12-20
        experience : DigEcon, Web developer
      - start : 2015-06-15
        end : 2016-06-20
        experience : 24TENDER, AmoCRM Integrator
      - start : 2011-03-15
        end : 2015-03-21
        experience : Radio Noyabrsk, Sound Engineer (and Wordpress site developer)
      - start : 2009-04-30
        end : 2017-03-20
        experience : Lazy Beat, Music box founder and developer
    skills :
      - skill : Ruby
        value : 89
      - skill : PostgreSQL
        value : 86
      - skill : Ruby on Rails
        value : 85
      - skill : Git/Github
        value : 77
      - skill : Continuous Integration
        value : 69
      - skill : Telegram bot
        value : 68
      - skill : PostGIS
        value : 23
      - skill : Sidekiq
        value : 75
      - skill : Javascript
        value : 59
      - skill : Vue.js
        value : 47
      - skill : Ubuntu Server
        value : 80
      - skill : Bitcoin Protocols
        value : 67
      - skill : IceCast2
        value : 55
      - skill : PHP
        value : 25

  # Icons
  icons :
    email: potehin@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/madmatvey/ # Full URL
    github: madmatvey
    twitter: EugeneLeontev
    facebook: madmatvey
    instagram: matvey_rl_zhook

  # Disqus
  disqus_shortname : madmatvey

# Pagination
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/blog/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'blog'
  autopages:
    enabled: false

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate-v2]
bootstrap:
  assets: true
